apiVersion: batch/v1
kind: Job
metadata:
  name: instant-python
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: instant-python
        image: python:3
        command:
        - "python"
        - "/script/main.py"
        volumeMounts:
        - mountPath: /script
          name: script
      volumes:
      - name: script
        configMap:
          name: instant-python-script
